# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20160131_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
